### ISSUE TITLE
Draft for Possible Repo Refactor for Standardization

### ISSUE THREAD

**Issue by adophilus** [sammychinedu2ky/Coding-Resources#32]
Good day everyone,

While going through the repo, I noticed a few inconsistencies with the naming of files in the various learning resources folder.

I thought of a possible way to simplify this. Below is the draft for what I came up with

### Repo Structure
```
Coding-Resources/
  Git/
    resources.json
    README.md (built)
  Python/
    resources.json
    README.md (built)
  ...
```

#### `resources.json`
- holds a list of resources related to the particular resource group (e.g: Python, Git, etc.)
- located in each resource folder
- used to generete `README.md` for resource

#### `README.md`
- the visual representation of the data in corresponding `resources.json`
- located in each resource folder
- generated from github workflow

I would really like it if you could look into this issue and give me some feedback on it

**Comment by sammychinedu2ky** [comment]
Hmm, interesting and thanks for the contribution 🤔, but how would you want to represent a long list of links visually

**Comment by adophilus** [comment]
There would be a compiler that would compile in from each resource's `resources.json` into the respective `README.md`. For example

```js
// Git/resources.json
[
  {
    "type": "pdf",
    "title": "Professional Git PDF",
    "link": "https://github.com/anzhihe/Free-Git-Books/blob/master/book/Professional%20Git.pdf",
    "description": "Professional PDF"
  },
  {
    "type": "pdf",
    "title": "The Pro Git Pdf",
    "link": "https://git-scm.com/book/en/v2",
    "description": "The official Pro Git PDF"
  }
]
```

```md
// compiled README.md
# Git Resources
- [#PDFs](PDFs)
 
## PDFs
- [https://github.com/anzhihe/Free-Git-Books/blob/master/book/Professional%20Git.pdf](Professional Git PDF)
- [https://git-scm.com/book/en/v2](The Pro Git Pdf)
```

**Comment by sammychinedu2ky** [comment]
That seems cool . Makes sense especially where the types vary.
You're also free to work on it, if you have the time 🙌

**Comment by adophilus** [comment]
alright. Thanks for the go ahead

**Comment by adophilus** [comment]
I have implemented the compiler. You can take a look at it [here](https://github.com/Adophilus/sammychinedu2ky-Coding-Resources/tree/main/resources/DataStructure%20and%20Algorithms). But because of the way it's setup, I would need to make a PR to the `dev` branch for the following reasons:
- devs would be able to make branch of `dev` if they want to add more resources
- the github action to compile the resources would trigger if the PR is accepted into main.

Could you create a `dev` branch so that I can set that as the base of my PR?

**Comment by sammychinedu2ky** [comment]
> I have implemented the compiler. You can take a look at it [here](https://github.com/Adophilus/sammychinedu2ky-Coding-Resources/tree/main/resources/DataStructure%20and%20Algorithms). But because of the way it's setup, I would need to make a PR to the `dev` branch for the following reasons:
> 
> * devs would be able to make branch of `dev` if they want to add more resources
> * the github action to compile the resources would trigger if the PR is accepted into main.
> 
> Could you create a `dev` branch so that I can set that as the base of my PR?

Thanks, @Adophilus , incredible work you did there🙌
The dev branch isn't critical. They could just make a pull request by adding more resources to the JSON file. then the action could be triggered once the pull request is merged and closed.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges

**Comment by adophilus** [comment]
alright then. I'll go ahead and open a PR
